[tool.poetry]
name = "yakka"
version = "0.1.0"
description = "Infrastructure for AI applications and machine learning pipelines"
authors = ["sam <sam@eventual.ai>"]
readme = "README.md"


[tool.poetry.dependencies]
aiobotocore = "^2.9.0"
botocore = ">=1.33.2,<1.33.14"
pandas = "^2.1.4"
pandera = "^0.18.0"
pydantic = "^2.5.3"
python = "3.12.1"
aws-lambda-typing = "^2.18.0"
types-aiobotocore = { extras = ["essential"], version = "^2.9.0" }

[tool.poetry.group.dev.dependencies]
matplotlib = "^3.8.2"
pylint = "^3.0.3"
pyright = "^1.1.345"
requests = "^2.31.0"
ruff = "^0.1.11"
streamlit = "^1.29.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
indent-width = 2
