[tool.poetry]
name = "app"

version = "0.1.0"
description = ""
authors = ["sam <sam@yakka.sh>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.12.1"
streamlit = "^1.29.0"
yakka = { path = "../../" }
types-aiobotocore = { extras = ["essential"], version = "^2.9.0" }


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
